# Generated by Django 5.1.4 on 2024-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0003_bookrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non_fiction", "Non-fiction"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
